In [113]:
import numpy as np # importance

### NUMPY ARRAY

In [114]:
myList:list = [20, 30, 40]
type(myList)

list

In [115]:
numArr = np.array(myList)
print("value: ", numArr)
print("type:", type(numArr))

value:  [20 30 40]
type: <class 'numpy.ndarray'>


In [ ]:
matrixArr:list = [[1, 2, 3], [3, 4, 5], [6, 7, 8]]
np.array(matrixArr) # nothing has changed except of view

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]])

In [117]:
easyList = range(0, 10, 1)  # 0 to 10 with step size '1'
print(list(easyList))  # we must change the type with list() function

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


##### NP.ARRANGE

In [118]:
a = np.arange(0, 10, 1) # same logic with range func. of python
b = np.arange(0, 10, 2) # same logic with range func. of python
print(a)
print(b)


[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


#### NP.ZEROS and NP.ONES

In [169]:
np.zeros(10) # gives a list full of zeros


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [120]:
np.ones(10) # gives a list full of ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### NP.LINSPACE

In [121]:
# It means, it gives a list which each of element has same distance between
np.linspace(0, 10, 5)  # Means, give me 3 numbers which have same distance between 0 and 10
# 0 and 10 are included

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

#### NP.EYE

In [122]:
# Don't know how to explain but if just look at the result you will understand
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### NP.RANDOM

In [123]:
np.random.rand(10) # gives random but meaningful data

array([0.23738088, 0.84545422, 0.98324081, 0.45510192, 0.70905493,
       0.26982774, 0.20079408, 0.94333997, 0.52745591, 0.83095492])

In [124]:
np.random.rand(3, 3) # gives a matrix structure

array([[0.18768597, 0.41633218, 0.03565362],
       [0.54418657, 0.20431263, 0.99055759],
       [0.18685854, 0.74630187, 0.12810348]])

In [125]:
np.random.randint(1, 1000) # gives random integer between parameters are given

899

In [126]:
np.random.randint(1, 1000, 5) # gives specific amount of numbers and so you will have a np list

array([794, 556, 366, 898, 395], dtype=int32)

## ARRAY METHODS

In [127]:
numpyList = np.random.randint(0, 20, 4) # we 4 numbers in our array
numpyList

array([19, 17,  8,  8], dtype=int32)

#### RESHAPE

In [128]:
numpyList.reshape(1, 4) # we have totally 4 numbers in our array so reshape parameters' multiplied result must give us total number

array([[19, 17,  8,  8]], dtype=int32)

In [129]:
reshapedList = numpyList.reshape(2, 2)
numpyList.reshape(2, 2)

array([[19, 17],
       [ 8,  8]], dtype=int32)

In [130]:
numpyList  # structure is not changed

array([19, 17,  8,  8], dtype=int32)

In [131]:
reshapedList # structure is changed

array([[19, 17],
       [ 8,  8]], dtype=int32)

In [132]:
numpyList.max() # gives a value from the array

np.int32(19)

In [133]:
numpyList.argmax() # gives an index

np.int64(0)

In [134]:
numpyList.min()

np.int32(8)

In [135]:
numpyList.argmin() # gives an index

np.int64(2)

#### SHAPE

In [136]:
numpyList.shape  # 4x1

(4,)

In [137]:
reshapedList.shape # 2x2

(2, 2)

# ARRAY INDEX METHODS

In [138]:
numArr = np.arange(0, 15)
numArr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [139]:
# GET INDEX
numArr[0]

np.int64(0)

In [140]:
# SLICE
numArr[0:5]

array([0, 1, 2, 3, 4])

In [141]:
# EDIT
numArr[0:5] = 3
numArr # values is changed

array([ 3,  3,  3,  3,  3,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [142]:
numArrN = np.arange(0, 24)
numArrN

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [143]:
mergedArray = numArrN[2:10]
mergedArray

array([2, 3, 4, 5, 6, 7, 8, 9])

In [144]:
mergedArray[:] = 2
mergedArray

array([2, 2, 2, 2, 2, 2, 2, 2])

In [145]:
numArrN # What the fuck moment
# this is about numpy state

array([ 0,  1,  2,  2,  2,  2,  2,  2,  2,  2, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [146]:
# to avoid this situation use '.copy()' func
nArr1 = np.arange(0, 24)
nArr2 = nArr1.copy()[2:10]
nArr2[:] = 2
print('nArr1: ', nArr1)
print('nArr2: ', nArr2)
# As a result, original values of nArr1 is not changed thanks to the .copy() method


nArr1:  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
nArr2:  [2 2 2 2 2 2 2 2]


## MATRIX INDEXES

In [ ]:
matrixArray:list = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
matrixArray = np.array(matrixArray)
matrixArray


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [148]:
matrixArray[0]

array([1, 2, 3])

In [ ]:
matrixArray[0][2]

np.int64(3)

In [153]:
# OR
matrixArray[0, 2]

np.int64(3)

In [ ]:
matrixArray[0][3] # error state 'out of range'

IndexError: index 3 is out of bounds for axis 0 with size 3

In [163]:
# useful usage
matrixArray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
matrixArray[0:,2] # so, give me 2. element of from 0 to end rows

array([3, 6, 9])

In [166]:
matrixArray[0:,0:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [167]:
matrixArray[0:,1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [172]:
newMatrixArr = np.random.randint(0, 25, 36).reshape(4, 9)
newMatrixArr

array([[23, 19, 23, 19, 18,  0,  2, 17, 13],
       [15,  0, 23, 10, 18, 17, 10, 13,  9],
       [ 5, 16,  3, 15, 24, 14, 12,  9, 24],
       [ 7, 17, 10, 24,  4, 14,  0, 23, 15]], dtype=int32)

In [174]:
newMatrixArr[[1, 3]]

array([[15,  0, 23, 10, 18, 17, 10, 13,  9],
       [ 7, 17, 10, 24,  4, 14,  0, 23, 15]], dtype=int32)

In [175]:
newMatrixArr[[1, 3]][0][[0, 4, 6]]

array([15, 18, 10], dtype=int32)

In [176]:
newMatrixArr[[1, 3]][1][[0, 4, 6]]

array([7, 4, 0], dtype=int32)

## OPERATIONS

In [180]:
newMatrixArray = np.random.randint(1, 100, 30)
newMatrixArray

array([80, 14, 34, 36, 49, 60, 82, 58, 14, 62, 48, 61, 92, 71, 33, 14, 80,
        8, 21, 43, 60, 58, 39, 47, 26, 27, 86, 62, 48, 32], dtype=int32)

In [181]:
newMatrixArray > 24

array([ True, False,  True,  True,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True,  True, False,  True, False,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [183]:
resultArray = newMatrixArray > 24
newMatrixArray[resultArray] # MAKE OUR LIVE EASIER!

array([80, 34, 36, 49, 60, 82, 58, 62, 48, 61, 92, 71, 33, 80, 43, 60, 58,
       39, 47, 26, 27, 86, 62, 48, 32], dtype=int32)

In [188]:
Arr = np.arange(0, 15); Arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [189]:
Arr + Arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [190]:
Arr * Arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196])

In [191]:
Arr / Arr

C:\Users\Furkan\AppData\Local\Temp\ipykernel_15376\857639192.py:1: RuntimeWarning: invalid value encountered in divide
  Arr / Arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.])

In [192]:
Arr - Arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [193]:
np.sqrt(Arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739])

In [194]:
np.max(Arr)

np.int64(14)

In [195]:
np.min(Arr)

np.int64(0)

In [ ]:
np.argmax(Arr) # index

np.int64(14)

In [ ]:
np.argmin(Arr) # index

np.int64(0)

## CONTINUE

https://numpy.org/doc/